---
# This override file is used for local development
# It will automatically be used by docker-compose when present
# This allows local builds with client assets while preserving CI/CD workflows

services:
  fundraiser-app:
    build:
      context: .
      dockerfile: src/GreatIdeas.WebAPI/Dockerfile.local
      # target: final # Build full multi-stage including client assets
    image: greatideasgh/fundraiser:local-dev
    container_name: fundraiser-local-dev
    environment:
      ASPNETCORE_ENVIRONMENT: "Staging"
      ApplicationSettings:Database:PostgresConnection: "Server=host.docker.internal;Port=5433;Database=FundraiserDb-staging;user id=appuser;password=adminPassword;pooling=true"
      ApplicationSettings:PaystackSettings:PublicKey: "pk_test_bfa08aa20317f1bc0a5d14dfbae7abc047726c09"
      ApplicationSettings:PaystackSettings:SecretKey: "sk_test_0f8d673902a2357e0b6329e85ceddeb8bf4e95ed"
      ApplicationSettings:PaystackSettings:IsEnabled: true
      # Development specific settings
      ASPNETCORE_URLS: "http://+:8080"
      Logging:LogLevel:Default: "Information"
    ports:
      - "7022:8080" # Different port to avoid conflicts with staging
    volumes:
      - fundraiser-local:/app/wwwroot/campaigns
      - fundraiser-local:/app/wwwroot/donations
    # Add development specific labels
    labels:
      - "fundraiser.environment=local"
      - "fundraiser.client.included=true"

volumes:
  fundraiser-local:
    driver: local
