//Autogenerated from Permissions.tt

using System.ComponentModel.DataAnnotations;

namespace GreatIdeas.Template.Application.Authorizations.PolicyDefinitions;

public static class AppPermissions
{
    public static class Account
    {
        [Display(Name = "ViewAccount")] public const string View = "View.Account";

        [Display(Name = "ManageAccount")] public const string Manage = "Manage.Account";

        [Display(Name = "DeleteAccount")] public const string Delete = "Delete.Account";
    }

    public static class Audit
    {
        [Display(Name = "ViewAudits")] public const string View = "View.AuditLogs";

        [Display(Name = "ManageAudits")] public const string Manage = "Manage.AuditLogs";
    }
}