//Autogenerated from Permissions.tt
using System.ComponentModel.DataAnnotations;

namespace GreatIdeas.Template.Application;

public static class AppPermissions
{ 

    public static class Staff
    {
        [Display(Name = "ViewStaff")]
        public const string View = "View.Staff";
        [Display(Name = "ManageStaff")]
        public const string Manage = "Manage.Staff";
        [Display(Name = "DeleteStaff")]
        public const string Delete = "Delete.Staff";
    }
     

    public static class Audit
    {
        [Display(Name = "ViewAudits")]
        public const string View = "View.AuditLogs";
        [Display(Name = "ManageAudits")]
        public const string Manage = "Manage.AuditLogs";
    }    
}