//Autogenerated from Permissions.tt
using System.ComponentModel.DataAnnotations;

namespace GreatIdeas.Template.Application.Authorizations.PolicyDefinitions;

public static class AppPermissions
{
    public static class Student
    {
        [Display(Name = "ViewStudent")]
        public const string View = "View.Student";

        [Display(Name = "ManageStudent")]
        public const string Manage = "Manage.Student";

        [Display(Name = "DeleteStudent")]
        public const string Delete = "Delete.Student";
    }

    public static class Staff
    {
        [Display(Name = "ViewStaff")]
        public const string View = "View.Staff";

        [Display(Name = "ManageStaff")]
        public const string Manage = "Manage.Staff";

        [Display(Name = "DeleteStaff")]
        public const string Delete = "Delete.Staff";
    }

    public static class Level
    {
        [Display(Name = "ViewLevel")]
        public const string View = "View.Level";

        [Display(Name = "ManageLevel")]
        public const string Manage = "Manage.Level";

        [Display(Name = "DownloadLevel")]
        public const string Download = "Download.Level";
    }

    public static class Unit
    {
        [Display(Name = "ViewUnit")]
        public const string View = "View.Unit";

        [Display(Name = "CreateUnit")]
        public const string Create = "Create.Unit";

        [Display(Name = "UpdateUnit")]
        public const string Update = "Update.Unit";

        [Display(Name = "ApproveUnit")]
        public const string Approve = "Approve.Unit";

        [Display(Name = "DeleteUnit")]
        public const string Delete = "Delete.Unit";
    }

    public static class Score
    {
        [Display(Name = "ViewScore")]
        public const string View = "View.Score";

        [Display(Name = "ManageScore")]
        public const string Manage = "Manage.Score";
    }

    public static class Cognitive
    {
        [Display(Name = "Cognitive.Translate")]
        public const string Translate = "Cognitive.Translate";

        [Display(Name = "Cognitive.TTS")]
        public const string TTS = "Cognitive.TTS";
    }

    public static class Audit
    {
        [Display(Name = "ViewAudits")]
        public const string View = "View.AuditLogs";

        [Display(Name = "ManageAudits")]
        public const string Manage = "Manage.AuditLogs";
    }
}
