@baseUrl = https://localhost:7139/api/accounts
@userId = f379957b-abfc-4728-9726-d37ee0baacd8
@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJiMWZjM2FjMi01MzRiLTRhNmEtOThkOC1hMzU0YTg1NDc1NGIiLCJpZCI6ImYzNzk5NTdiLWFiZmMtNDcyOC05NzI2LWQzN2VlMGJhYWNkOCIsInVzZXJuYW1lIjoiYWRtaW4iLCJuYW1lIjoiQWRtaW4gTmFtZSIsImVtYWlsIjoiYWRtaW5AZW1haWwuY29tIiwicm9sZSI6IkFkbWluIiwicGVybWlzc2lvbiI6WyJWaWV3LkFjY291bnQiLCJNYW5hZ2UuQWNjb3VudCIsIkRlbGV0ZS5BY2NvdW50IiwiVmlldy5BdWRpdExvZ3MiLCJNYW5hZ2UuQXVkaXRMb2dzIl0sIm5iZiI6MTc0Nzc5NjA3MCwiZXhwIjoxNzQ3ODA2ODcwLCJpYXQiOjE3NDc3OTYwNzAsImlzcyI6IkdyZWF0SWRlYXMuVGVtcGxhdGUuV2ViQVBJIiwiYXVkIjoiR3JlYXRJZGVhcy5UZW1wbGF0ZS5XZWJBUEkifQ.cuRDqxYRKlsFaPBFeyMrhkDqmbJxNcODozKQh48fl9o

### Login 

POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "admin",
  "password": "P@ssword1"
}

### Get account
GET {{baseUrl}}/{{userId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

### Create account 

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "username": "geralds@email.com",
  "fullName": "Gerald Maale",
  "email": "geralds@email.com",
  "phoneNumber": "0210000002",
  "role": "Admin",
  "password": "P@ssword1",
  "confirmPassword": "P@ssword1"
}

### Update profile

PATCH {{baseUrl}}/{{userId}}/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "fullName": "Gerald Maale",
  "phoneNumber": "0210000002"
}

### Update account

PUT {{baseUrl}}/{{userId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "fullName": "Gerald Maale",
  "username": "gerald@email.com",
  "email": "gerald@email.com",
  "phoneNumber": "0210000033",
  "isActive": true,
  "role": "Admin"
}

### Get paged accounts
GET {{baseUrl}}/paged?pageNumber=1&pageSize=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{bearerToken}}