//Autogenerated from Permissions.tt
using System.ComponentModel.DataAnnotations;

namespace Company.Project.Application.Authorizations.PolicyDefinitions;

public static class AppPermissions
{ 

    public static class Account
    {
        [Display(Name = "ViewAccount")]
        public const string View = "View.Account";
        [Display(Name = "ManageAccount")]
        public const string Manage = "Manage.Account";
        [Display(Name = "DeleteAccount")]
        public const string Delete = "Delete.Account";
    }

    public static class Campaign
    {
        [Display(Name = "ViewCampaign")]
        public const string View = "View.Campaign";
        [Display(Name = "ManageCampaign")]
        public const string Manage = "Manage.Campaign";
        [Display(Name = "DeleteCampaign")]
        public const string Delete = "Delete.Campaign";
    }

    public static class Donation
    {
        [Display(Name = "ViewDonation")]
        public const string View = "View.Donation";
        [Display(Name = "ManageDonation")]
        public const string Manage = "Manage.Donation";
        [Display(Name = "DeleteDonation")]
        public const string Delete = "Delete.Donation";
    }

    public static class Donor
    {
        [Display(Name = "ViewDonor")]
        public const string View = "View.Donor";
        [Display(Name = "ManageDonor")]
        public const string Manage = "Manage.Donor";
        [Display(Name = "DeleteDonor")]
        public const string Delete = "Delete.Donor";
    }
     

    public static class Audit
    {
        [Display(Name = "ViewAudits")]
        public const string View = "View.AuditLogs";
        [Display(Name = "ManageAudits")]
        public const string Manage = "Manage.AuditLogs";
    }  

    public static class Dashboard
    {
        [Display(Name = "ViewDashboard")]
        public const string View = "View.Dashboard";
    }

    public static class Settings
    {
        [Display(Name = "ViewSettings")]
        public const string View = "View.Settings";
        [Display(Name = "ManageSettings")]
        public const string Manage = "Manage.Settings";
    }

    public static class Reports
    {
        [Display(Name = "ViewReports")]
        public const string View = "View.Reports";
    }
}