 @baseUrl = http://localhost:5000/api/audits
@bearerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.xxx.xxx

# Get audits pagination

GET {{baseUrl}}/paged?pageNumber=1&pageSize=10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{bearerToken}}


### Get audit log

GET {{baseUrl}}/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{bearerToken}}
