name: Build Solution

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  BUILD_CONFIGURATION: "Release" # set this to the appropriate build configuration
  PROJECT_PATH: "templates/content/webapi/GreatIdeas.Template.sln" # set this to the solution file name

jobs:
  build_test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 9.x

      # Run dotnet build and package
      - name: dotnet build
        run: |
          dotnet restore dotnet build .\templates\content\webapi\GreatIdeas.Template.sln
          dotnet build ${{env.PROJECT_PATH}} --configuration '${{ env.BUILD_CONFIGURATION }}' --tl
