name: Build and Test Solution

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

env:
  BUILD_CONFIGURATION: "Release" # set this to the appropriate build configuration

jobs:
  build_test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 9.x

      # Run dotnet build and package
      - name: dotnet build and test
        run: |
          dotnet restore
          dotnet build --configuration '${{ env.BUILD_CONFIGURATION }}' --tl
          dotnet test --configuration '${{ env.BUILD_CONFIGURATION }}' --tl
